name: scikit-learn-env
channels:
    - defaults
dependencies:
  - python=3.6.2
  - pip
  - pip:
    - azureml-defaults
    - azureml-widgets
    - azureml-sdk
    - joblib
    - lightgbm
    - inference-schema[numpy-support]
    - imblearn
    - imbalanced-learn
  - numpy
  - pandas
  - scikit-learn
