name: Linting

on:
  workflow_dispatch:

jobs:
  build:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Install Pytest
      run: |
        python -m pip install -r requirements.txt
    - name: Run linting tests
      run: | 
        flake8 src/model/
    - name: Run unit test
      run: |
        pytest tests/
